# coding: utf-8

"""
    Yodlee Core APIs

    This file describes the Yodlee Platform APIs, using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, javascript, PHP or other languages according to your development needs. For more details about our APIs themselves, please refer to https://developer.yodlee.com/Yodlee_API/.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: developer@yodlee.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AccountMigrationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'provider_id': 'int',
        'provider_account_id': 'int'
    }

    attribute_map = {
        'provider_id': 'providerId',
        'provider_account_id': 'providerAccountId'
    }

    def __init__(self, provider_id=None, provider_account_id=None):  # noqa: E501
        """AccountMigrationResponse - a model defined in Swagger"""  # noqa: E501

        self._provider_id = None
        self._provider_account_id = None
        self.discriminator = None

        if provider_id is not None:
            self.provider_id = provider_id
        if provider_account_id is not None:
            self.provider_account_id = provider_account_id

    @property
    def provider_id(self):
        """Gets the provider_id of this AccountMigrationResponse.  # noqa: E501


        :return: The provider_id of this AccountMigrationResponse.  # noqa: E501
        :rtype: int
        """
        return self._provider_id

    @provider_id.setter
    def provider_id(self, provider_id):
        """Sets the provider_id of this AccountMigrationResponse.


        :param provider_id: The provider_id of this AccountMigrationResponse.  # noqa: E501
        :type: int
        """

        self._provider_id = provider_id

    @property
    def provider_account_id(self):
        """Gets the provider_account_id of this AccountMigrationResponse.  # noqa: E501


        :return: The provider_account_id of this AccountMigrationResponse.  # noqa: E501
        :rtype: int
        """
        return self._provider_account_id

    @provider_account_id.setter
    def provider_account_id(self, provider_account_id):
        """Sets the provider_account_id of this AccountMigrationResponse.


        :param provider_account_id: The provider_account_id of this AccountMigrationResponse.  # noqa: E501
        :type: int
        """

        self._provider_account_id = provider_account_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountMigrationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountMigrationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
